---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: discourse
  namespace: default
spec:
  chart:
    spec:
      chart: bitnamicharts/discourse
      version: "~10"
      sourceRef:
        kind: HelmRepository
        name: dockerhub
      interval: 5m
  interval: 2m
  values:
    host: localhost:8080
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: localhost
    extraEnvVarsCM:
      - discourse-config
