---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: discourse
  namespace: default
spec:
  chart:
    spec:
      chart: bitnamicharts/discourse
      version: "~10"
      sourceRef:
        kind: HelmRepository
        name: dockerhub
      interval: 5m
  interval: 2m
  values:
    host: localhost:8080
    discourse:
      plugins:
        - https://github.com/Mbond65/discourse_user_auto_activation
        - https://github.com/discourse/discourse-solved
        - https://github.com/discourse/discourse-spoiler-alert
        - https://github.com/discourse/discourse-sublime-theme
      livenessProbe:
        initialDelaySeconds: 60
        failureThreshold: 100
        periodSeconds: 20
      readinessProbe:
        failureThreshold: 10
        periodSeconds: 20
      startupProbe:
        enabled: true
        periodSeconds: 10
        failureThreshold: 100
