---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dockerhub
  namespace: default
spec:
  type: "oci"
  interval: 5m
  url: oci://registry-1.docker.io
  provider: generic
  secretRef:
    name: docker-auth
