---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: examiner
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: discourse
                port:
                  number: 80
            path: /
            pathType: Prefix
